
version: "3.0"

networks:
  alvarium:
    driver: bridge

services:
  publisher:
    container_name: publisher
    hostname: publisher
    entrypoint:
      - java
      - -jar
      - ./out.jar
      - transit-1
    depends_on:
      - transit-1
    build:
      args:
        name: publisher
      context: ..
      dockerfile: docker/scala-node.dockerfile
    networks:
      - alvarium

  transit-1:
    container_name: transit-1
    hostname: transit-1
    entrypoint:
      - java
      - -jar
      - ./out.jar
      - transit-2
    depends_on:
      - transit-2
    build:
      args:
        name: transit
      context: ..
      dockerfile: docker/scala-node.dockerfile
    networks:
      - alvarium

  transit-2:
    container_name: transit-2
    hostname: transit-2
    devices:
      - /dev/tpm0:/dev/tpm0
    build:
      args:
        name: transit
      context: ..
      dockerfile: docker/scala-node.dockerfile
    networks:
      - alvarium

  mosquitto-server:
    container_name: mosquitto-server
    image: eclipse-mosquitto:latest
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
    networks:
      - alvarium


  mosquitto-client:
    container_name: mosquitto-client
    depends_on:
      - mosquitto-server
    build:
      context: ..
      dockerfile: docker/mosquitto-client.dockerfile
    networks:
      - alvarium
